/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Carlos
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMédicos = new javax.swing.JMenu();
        jMenuItemCadastroMedicos = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenu();
        jMenuItemCadastroPacientes = new javax.swing.JMenuItem();
        jMenuPlanosSaude = new javax.swing.JMenu();
        jMenuItemCadastroPSaude = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuMédicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medico32px.png"))); // NOI18N
        jMenuMédicos.setText("Médicos");

        jMenuItemCadastroMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medico24px.png"))); // NOI18N
        jMenuItemCadastroMedicos.setText("Cadastro de Médicos");
        jMenuItemCadastroMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroMedicosActionPerformed(evt);
            }
        });
        jMenuMédicos.add(jMenuItemCadastroMedicos);

        jMenuBar1.add(jMenuMédicos);

        jMenuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente32px.png"))); // NOI18N
        jMenuPacientes.setText("Pacientes");

        jMenuItemCadastroPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente24px.png"))); // NOI18N
        jMenuItemCadastroPacientes.setText("Cadastro de Pacientes");
        jMenuItemCadastroPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPacientesActionPerformed(evt);
            }
        });
        jMenuPacientes.add(jMenuItemCadastroPacientes);

        jMenuBar1.add(jMenuPacientes);

        jMenuPlanosSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planos32px.png"))); // NOI18N
        jMenuPlanosSaude.setText("Planos de Saúde");

        jMenuItemCadastroPSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planos32px.png"))); // NOI18N
        jMenuItemCadastroPSaude.setText("Cadastro de Planos de Saúde");
        jMenuItemCadastroPSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPSaudeActionPerformed(evt);
            }
        });
        jMenuPlanosSaude.add(jMenuItemCadastroPSaude);

        jMenuBar1.add(jMenuPlanosSaude);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroMedicosActionPerformed
        // TODO add your handling code here:
        
        MedicoView medicoView = new MedicoView();
        medicoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroMedicosActionPerformed

    private void jMenuItemCadastroPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPacientesActionPerformed
        // TODO add your handling code here:
        
        PacienteView pacienteView = new PacienteView();
        pacienteView.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroPacientesActionPerformed

    private void jMenuItemCadastroPSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPSaudeActionPerformed
        // TODO add your handling code here:
        
        PlanoSaudeView pSaudeView = new PlanoSaudeView();
        pSaudeView.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroPSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroMedicos;
    private javax.swing.JMenuItem jMenuItemCadastroPSaude;
    private javax.swing.JMenuItem jMenuItemCadastroPacientes;
    private javax.swing.JMenu jMenuMédicos;
    private javax.swing.JMenu jMenuPacientes;
    private javax.swing.JMenu jMenuPlanosSaude;
    // End of variables declaration//GEN-END:variables
}
